# Abathur Configuration
# Override settings by editing this file or setting environment variables
# with ABATHUR_ prefix
#
# Example environment variables:
#   export ABATHUR_MAX_AGENTS=20
#   export ABATHUR_RATE_LIMIT__REQUESTS_PER_SECOND=15.0
#   export ABATHUR_DATABASE__PATH=/custom/path/abathur.db
#   export ABATHUR_LOGGING__LEVEL=debug

# Maximum concurrent agents (1-100)
max_agents: 10

# Database configuration
database:
  # Path to SQLite database file (project-local)
  path: ".abathur/abathur.db"

  # Maximum number of database connections in pool
  max_connections: 10

# Logging configuration
logging:
  # Log level: trace, debug, info, warn, error
  level: "info"

  # Log format: json, pretty
  format: "json"

  # Number of days to retain logs
  retention_days: 30

# Claude API rate limiting
rate_limit:
  # Requests per second allowed
  requests_per_second: 10.0

  # Burst size for token bucket algorithm
  burst_size: 20

# Retry policy for transient failures
retry:
  # Maximum number of retry attempts
  max_retries: 3

  # Initial backoff delay in milliseconds
  initial_backoff_ms: 10000

  # Maximum backoff delay in milliseconds
  max_backoff_ms: 300000

# MCP (Model Context Protocol) server configurations
mcp_servers:
  - name: "memory"
    command: "npx"
    args:
      - "-y"
      - "@modelcontextprotocol/server-memory"
    env: {}

  - name: "github"
    command: "npx"
    args:
      - "-y"
      - "@modelcontextprotocol/server-github"
    env: {}

# LLM Substrate configuration
# Abathur supports multiple LLM backends (substrates)
substrates:
  # Default substrate to use (claude-code, anthropic-api)
  default_substrate: "claude-code"

  # List of enabled substrates
  enabled:
    - "claude-code"
    # - "anthropic-api"  # Uncomment to enable Anthropic API

  # Claude Code CLI configuration (default substrate)
  # Requires: claude CLI to be installed and authenticated
  # No API key needed - uses Claude Code's auth
  claude_code:
    claude_path: "claude"
    timeout_secs: 300

  # Anthropic API configuration (optional substrate)
  # Requires: ANTHROPIC_API_KEY environment variable or api_key below
  anthropic_api:
    enabled: false
    # api_key: "sk-..."  # Optional: defaults to ANTHROPIC_API_KEY env var
    model: "claude-3-5-sonnet-20241022"

  # Agent type to substrate mappings (optional)
  # Maps specific agent types to preferred substrates
  # If not specified, uses default_substrate
  agent_mappings: {}
    # Example mappings:
    # rust-specialist: "claude-code"
    # requirements-gatherer: "anthropic-api"
