//! Built-in reactive event handlers (split module).
//!
//! All handlers are **idempotent** — safe to run even if the poll loop already
//! handled the same state change. They check current state before acting.

mod helpers;

mod a2a_poll;
mod adapter_lifecycle_sync;
mod agent_termination;
mod budget_opportunity;
mod budget_token_accumulator;
mod convergence_cancellation;
mod convergence_coordination;
mod convergence_escalation_feedback;
mod convergence_evolution;
mod convergence_memory;
mod convergence_sla_pressure;
mod dead_letter_retry;
mod direct_mode_execution_memory;
mod egress_routing;
mod escalation_timeout;
mod event_pruning;
mod event_store_poller;
mod evolution_evaluation;
mod evolution_triggered_template_update;
mod fast_reconciliation;
mod goal_convergence_check;
mod goal_created;
mod goal_evaluation;
mod goal_evaluation_task_creation;
mod goal_reconciliation;
mod goal_retired;
mod goal_stagnation_detector;
mod ingestion_poll;
mod memory_conflict_escalation;
mod memory_informed_decomposition;
mod memory_maintenance;
mod memory_reconciliation;
mod obstacle_escalation;
mod priority_aging;
mod ready_task_polling;
mod reconciliation;
mod retry_processing;
mod review_failure_loop;
mod specialist_check;
mod startup_catch_up;
mod stats_update;
mod system_stall_detector;
mod task_completed_readiness;
mod task_completion_learning;
mod task_failed_block;
mod task_failed_retry;
mod task_outcome_memory;
mod task_ready_spawn;
mod task_schedule;
mod task_sla_enforcement;
mod trigger_catchup;
mod watermark_audit;
mod workflow_subtask_completion;
mod workflow_verification;
mod worktree_reconciliation;

#[cfg(test)]
pub(super) mod test_support;

pub(crate) use helpers::{try_update_task, update_with_retry};

pub use a2a_poll::A2APollHandler;
pub use adapter_lifecycle_sync::AdapterLifecycleSyncHandler;
pub use agent_termination::AgentTerminationHandler;
pub use budget_opportunity::BudgetOpportunityHandler;
pub use budget_token_accumulator::BudgetTokenAccumulatorHandler;
pub use convergence_cancellation::ConvergenceCancellationHandler;
pub use convergence_coordination::ConvergenceCoordinationHandler;
pub use convergence_escalation_feedback::ConvergenceEscalationFeedbackHandler;
pub use convergence_evolution::ConvergenceEvolutionHandler;
pub use convergence_memory::ConvergenceMemoryHandler;
pub use convergence_sla_pressure::ConvergenceSLAPressureHandler;
pub use dead_letter_retry::DeadLetterRetryHandler;
pub use direct_mode_execution_memory::DirectModeExecutionMemoryHandler;
pub use egress_routing::EgressRoutingHandler;
pub use escalation_timeout::EscalationTimeoutHandler;
pub use event_pruning::EventPruningHandler;
pub use event_store_poller::EventStorePollerHandler;
pub use evolution_evaluation::EvolutionEvaluationHandler;
pub use evolution_triggered_template_update::EvolutionTriggeredTemplateUpdateHandler;
pub use fast_reconciliation::FastReconciliationHandler;
pub use goal_convergence_check::GoalConvergenceCheckHandler;
pub use goal_created::GoalCreatedHandler;
pub use goal_evaluation::GoalEvaluationHandler;
pub use goal_evaluation_task_creation::GoalEvaluationTaskCreationHandler;
pub use goal_reconciliation::GoalReconciliationHandler;
pub use goal_retired::GoalRetiredHandler;
pub use goal_stagnation_detector::GoalStagnationDetectorHandler;
pub use ingestion_poll::IngestionPollHandler;
pub use memory_conflict_escalation::MemoryConflictEscalationHandler;
pub use memory_informed_decomposition::MemoryInformedDecompositionHandler;
pub use memory_maintenance::MemoryMaintenanceHandler;
pub use memory_reconciliation::MemoryReconciliationHandler;
pub use obstacle_escalation::ObstacleEscalationHandler;
pub use priority_aging::PriorityAgingHandler;
pub use ready_task_polling::ReadyTaskPollingHandler;
pub use reconciliation::ReconciliationHandler;
pub use retry_processing::RetryProcessingHandler;
pub use review_failure_loop::ReviewFailureLoopHandler;
pub use specialist_check::SpecialistCheckHandler;
pub use startup_catch_up::StartupCatchUpHandler;
pub use stats_update::StatsUpdateHandler;
pub use system_stall_detector::SystemStallDetectorHandler;
pub use task_completed_readiness::TaskCompletedReadinessHandler;
pub use task_completion_learning::TaskCompletionLearningHandler;
pub use task_failed_block::TaskFailedBlockHandler;
pub use task_failed_retry::TaskFailedRetryHandler;
pub use task_outcome_memory::TaskOutcomeMemoryHandler;
pub use task_ready_spawn::TaskReadySpawnHandler;
pub use task_schedule::TaskScheduleHandler;
pub use task_sla_enforcement::TaskSLAEnforcementHandler;
pub use trigger_catchup::TriggerCatchupHandler;
pub use watermark_audit::WatermarkAuditHandler;
pub use workflow_subtask_completion::WorkflowSubtaskCompletionHandler;
pub use workflow_verification::WorkflowVerificationHandler;
pub use worktree_reconciliation::WorktreeReconciliationHandler;
