# Minimum Supported Rust Version
msrv = "1.83"

# Complexity thresholds
cognitive-complexity-threshold = 30

# Avoid noisy lints
avoid-breaking-exported-api = true

# Warn on all wildcard imports
warn-on-all-wildcard-imports = true
