//! Post-completion middleware: create a pull request for standalone tasks.
//!
//! Only runs when:
//! - `tree_handled` is not set (tree tasks ship as whole via AutoshipMiddleware),
//! - verification passed, PRs are preferred, commits are required,
//! - the output delivery mode isn't `DirectMerge` (that bypasses PR creation).
//!
//! If PR creation succeeds, marks `tree_handled = true` so the merge-queue
//! middleware doesn't also run (preserving the previous `return Ok(())`).

use async_trait::async_trait;

use crate::domain::errors::DomainResult;
use crate::domain::models::workflow_template::OutputDelivery;
use crate::services::swarm_orchestrator::types::SwarmEvent;
use crate::services::{AuditAction, AuditCategory};

use super::super::helpers::{
    summarize_branch_changes, truncate_description, try_create_pull_request,
};
use super::{PostCompletionContext, PostCompletionMiddleware};

pub struct PullRequestMiddleware;

impl PullRequestMiddleware {
    pub fn new() -> Self {
        Self
    }
}

impl Default for PullRequestMiddleware {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl PostCompletionMiddleware for PullRequestMiddleware {
    fn name(&self) -> &'static str {
        "pull-request"
    }

    async fn handle(&self, ctx: &mut PostCompletionContext) -> DomainResult<()> {
        if ctx.tree_handled {
            return Ok(());
        }

        if !(ctx.verification_passed
            && ctx.prefer_pull_requests
            && ctx.require_commits
            && ctx.output_delivery != OutputDelivery::DirectMerge)
        {
            return Ok(());
        }

        let task_id = ctx.task_id;
        let Ok(Some(worktree)) = ctx.worktree_repo.get_by_task(task_id).await else {
            return Ok(());
        };

        let (pr_title, pr_body) = if let Ok(Some(task)) = ctx.task_repo.get(task_id).await {
            let intent = truncate_description(&task.description, 300);
            let changes =
                summarize_branch_changes(&worktree.path, &worktree.branch, &ctx.default_base_ref)
                    .await;
            let mut body = String::new();
            if !intent.is_empty() {
                body.push_str("## Summary\n\n");
                body.push_str(&intent);
                body.push_str("\n\n");
            }
            if !changes.is_empty() {
                body.push_str("## Changes\n\n");
                body.push_str(&changes);
                body.push('\n');
            }
            body.push_str(
                "\n---\nGenerated by [Abathur Swarm](https://github.com/abathur-swarm)\n",
            );
            (task.title.clone(), body)
        } else {
            (format!("Task {}", task_id), String::new())
        };

        if let Some(pr_url) = try_create_pull_request(
            &worktree.path,
            &worktree.branch,
            &pr_title,
            &pr_body,
            &ctx.default_base_ref,
        )
        .await
        {
            let _ = ctx
                .event_tx
                .send(SwarmEvent::PullRequestCreated {
                    task_id,
                    pr_url: pr_url.clone(),
                    branch: worktree.branch.clone(),
                })
                .await;

            ctx.audit_log
                .info(
                    AuditCategory::Task,
                    AuditAction::TaskCompleted,
                    format!("Task {} PR created: {}", task_id, pr_url),
                )
                .await;

            // PR created; merge-queue should not also run.
            ctx.tree_handled = true;
        } else {
            ctx.audit_log
                .info(
                    AuditCategory::Task,
                    AuditAction::TaskCompleted,
                    format!(
                        "Task {} PR creation failed, falling back to merge queue",
                        task_id
                    ),
                )
                .await;
        }

        Ok(())
    }
}
